[theme]
name = 'Bibata Cursor'
comment = 'Bibata is open source, compact, and material designed cursor set.'
website = 'https://www.github.com/ful1e5/Bibata_Cursor'

[config]
bitmaps_dir = '' # This config will assigned with `ctgen -d <path>`
out_dir = 'themes'
platforms = ['x11', 'windows']

[cursors]
[cursors.fallback_settings]
x11_sizes = [16, 20, 22, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]
win_sizes = [24, 28, 32, 48]
x_hotspot = 100
y_hotspot = 100
x11_delay = 40
win_delay = 1

[cursors.bd_double_arrow]
png = 'bd_double_arrow.png'
win_name = 'Dgn1'
x11_name = 'bd_double_arrow'
x11_symlinks = ["c7088f0f3e6c8088236ef8e1e3e70000", "nwse-resize", "size_fdiag"]

[cursors.bottom_left_corner]
png = 'bottom_left_corner.png'
x_hotspot = 7  # Adjusted value for 25% size
y_hotspot = 43  # Adjusted value for 25% size
x11_name = 'bottom_left_corner'
x11_symlinks = ["sw-resize"]

[cursors.bottom_right_corner]
png = 'bottom_right_corner.png'
x_hotspot = 43  # Adjusted value for 25% size
y_hotspot = 43  # Adjusted value for 25% size
x11_name = 'bottom_right_corner'
x11_symlinks = ['se-resize']

[cursors.bottom_side]
png = 'bottom_side.png'
x_hotspot = 25  # Adjusted value for 25% size
y_hotspot = 41  # Adjusted value for 25% size
x11_name = 'bottom_side'
x11_symlinks = ['s-resize']

[cursors.bottom_tee]
png = 'bottom_tee.png'
x_hotspot = 25  # Adjusted value for 25% size
y_hotspot = 41  # Adjusted value for 25% size
x11_name = 'bottom_tee'

# ... (repeat similar adjustments for other cursor entries)

[cursors.zoom_out]
png = 'zoom-out.png'
x_hotspot = 22  # Adjusted value for 25% size
y_hotspot = 22  # Adjusted value for 25% size
win_name = 'Zoom-out'
x11_name = 'zoom-out'

[cursors.person]
png = 'person.png'
x_hotspot = 10  # Adjusted value for 25% size
y_hotspot = 4   # Adjusted value for 25% size
win_name = 'Person'

[cursors.pin]
png = 'pin.png'
x_hotspot = 10  # Adjusted value for 25% size
y_hotspot = 4   # Adjusted value for 25% size
win_name = 'Pin'
